import MarketingFooter from "@/components/layouts/MarketingFooter"
import NavBarHeader from "@/components/layouts/NavBarHeader"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";

import "@aws-amplify/ui-react/styles.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <NavBarHeader></NavBarHeader>
          {children}
          <MarketingFooter></MarketingFooter>
        </main>
      </body>
    </html>
  );
}
