import { Amplify } from "aws-amplify";
import outputs from "@/amplify_outputs.json";
Amplify.configure(outputs);

import Header from "@/components/layouts/Header"
import Footer from "@/components/layouts/Footer"
import { SessionProvider } from '@/context/SessionContext';
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./app.css";
import "@aws-amplify/ui-react/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ふどうさん",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <main>
            <Header />
            {children}
            <Footer />
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
