import Header from "@/components/layouts/Header"
import Footer from "@/components/layouts/Footer"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";

import "@aws-amplify/ui-react/styles.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header></Header>

          {children}

          <Footer></Footer>
        </main>
      </body>
    </html>
  );
}
